### ISSUE TITLE
Update interactions for adding a new property to the CSS property editor

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast-dna#1789] opened 2019-05-23 17:29 UTC
**Interaction on adding a new property**

Different options

option a:
- Clicking once to the right of the class name, will add an empty property to the top of the group.
- Clicking twice to the right of the class name, will add the empty property to the bottom of the group

option b:
- Clicking to the right of a style property will add an empty property below it.

option c:
- Clicking at the bottom of the style group, will add an empty property to bottom of the group.

option d:
- Tabbing through the styles, will add an empty property when it gets to the bottom of the style group

**Comment by janechu** [comment] 2019-06-11 19:39
Duplicate of #1730

**Closed by janechu** 2019-06-11 19:39 UTC
Labels: issue : task
