### ISSUE TITLE
ContextMenu component not taking active focus when tabbing in fast-components-react-msft

### ISSUE THREAD

**Issue by therealAJ** [microsoft/fast-dna#2407] opened 2019-11-06 05:46 UTC
**Describe the bug; what happened?**
In reference to https://github.com/microsoft/fast-dna/issues/2329, focus is being skipped on the context-menu-item component.  cc @chrisdholt @scomea 

**What are the steps to reproduce the issue?**

Tab in ContextMenu, with arbitrary number of ContextMenuItem components as children, when open to see focus being skipped on ContextMenuItems. 

**What behavior did you expect?**

Expected behaviour, from W3 (https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal)

According to Aria spec focus should remain within modals - "Like non-modal dialogs, modal dialogs contain their tab sequence. That is, Tab and Shift + Tab do not move focus outside the dialog. However, unlike most non-modal dialogs, modal dialogs do not provide means for moving keyboard focus outside the dialog window without closing the dialog."

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Edge, Chrome, Safari, FireFox]
* Version [e.g. 1.8.0]

**Is there any additional context?**

I was hoping it would be possible to add this to the ContextMenu and ContextMenuItem components as well.

**Comment by chrisdholt** [comment] 2019-11-08 18:42
Thanks @therealAJ - Is the expectation to have a context menu behave as though it's a modal dialog or is this a context menu within a modal dialog not receiving focus?

**Comment by chrisdholt** [comment] 2019-11-12 19:57
@therealAJ Based on the detail below, I think there's an inaccurate expectation of the interaction model. For the context menu, we've followed the interaction model for a menu. I would expect that when paired with a button that opens it, the button would follow the [menu button](https://w3c.github.io/aria-practices/#menubutton) specification.

The models for keyboarding are quite different, but primarily, tab and shift tab do fundamentally things between a dialog and menu. I'm going to close this as by design, but feel free to open if I've misunderstood.

**Closed by chrisdholt** 2019-11-12 19:57 UTC
Labels: status : needs information
