### ISSUE TITLE
Add trailing comments on non-apparent colors in style packages

### ISSUE THREAD

**Issue by nalogiudice** [Microsoft/fast-dna#648] opened 2018-07-09 21:07 UTC
In situations where we use Chroma or our own custom methods to mix design system colors for JSS output, the color is obfuscated. I suggest leaving a trailing comment to show the outputted color.

For example, in the following JSS statement, the output of`applyMixedColor(foregroundColor, backgroundColor, .86)` is unknown:

```border: `${toPx(1)} solid ${applyMixedColor(foregroundColor, backgroundColor, .86)}```

I suggest a trailing comment such as:

```border: `${toPx(1)} solid ${applyMixedColor(foregroundColor, backgroundColor, .86)} \\ rgb(219,219,219)```

or

```border: `${toPx(1)} solid ${applyMixedColor(foregroundColor, backgroundColor, .86)} \\ #DBDBBDB)```

If there are multiple, we could simply seperate by commas (e.g. `\\ #DBDBDBD, #FEFEFE, #F4F4F4`)

**Comment by nicholasrice** [comment] 2018-07-10 22:40
What is the value add here? To me, this seems to increase maintenance costs and opportunity for comments to become misaligned with the actual color value. I'm not necessarily opposed but I want to understand how this will aid development - it's never really been a need is our past projects.

**Comment by chrisdholt** [comment] 2018-07-10 22:42
Agree with the above, the color is dynamic so we really can't with confidence provide an exact color match because it's all "config" based and not related to a certain color. We have defaults, but in the styles we are referencing the idea of a color, not an exact color.

**Comment by chrisdholt** [comment] 2018-07-16 06:30
Moving this to a proposal based on the notes above.

**Comment by awentzel** [comment] 2018-07-24 18:04
Similar concerns as others around maintainability and value.

**Comment by chrisdholt** [comment] 2018-07-24 18:11
I think that #728 will address some of this with the rework of the color system. For me, the moment a design system color is updated or changed any Chroma generated values which are based on them are different. I elect we close this as it will likely increase confusion.

**Comment by chrisdholt** [comment] 2018-07-24 19:36
Closing as this is by design and in favor of #728

**Closed by chrisdholt** 2018-07-24 19:36 UTC
Labels: proposal, reason : by design
