### ISSUE TITLE
Update navigation component to ensure scrolling works

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#351] opened 2018-04-30 22:01 UTC
User originally reported on VSTS:

**We need to validate that this problem does not exist on Fast-DNA** as soon as navigation component is complete and running in a page.

1. Run docs on localhost (npm run dev-server:docs)
2. Go to 'Building Blocks'
3. Make sure that your browser has the ability to scroll (if you are on a large monitor, shorten the height of your window to ensure a proper repro)
4. scroll so that 'Hero item' is at the top of the browser
5. Click hero item link or image

Notice that you are not taking to the top of the page, but rather to the new page at the same scroll area that you were previously at.

Expected: Clicking on any link takes you to the top of the new page

Actual: Clicking on a link when your browser window has been scrolled moves you to the new page content that matches the scroll height

**Comment by nicholasrice** [comment] 2018-05-05 02:04
@awentzel I don't believe this will be an issue with the `fast-dna` development site.

@Falkicon please correct me if I'm wrong, but I believe the site uses a more "full-screen" design-pattern where the view *itself* will never scroll, but panes inside the grid will scroll individually. The bug described above arises when the `window` is scrolled and a page-navigation takes place. Since the `window` doesn't scroll in this implementation, this should never be an issue.

I would recommend closing this because:
a. It does not currently repro
b. Based on my understanding of our site design, it will *never* repro with the steps described above.

@awentzel if you agree, can you close this issue?

**Comment by chrisdholt** [comment] 2018-05-17 23:11
@awentzel can we close this issue?

**Comment by chrisdholt** [comment] 2018-05-19 23:40
Closing for now due to points (a) and (b) noted above. If this issue shows up again, we can reopen the issue or create a new issue with more pertinent repro steps. As of now, this issue is outdated and not able to be reproduced in our current architecture so keeping the issue open doesn't seem to make much sense.

**Closed by chrisdholt** 2018-05-19 23:40 UTC
Labels: issue : bug
