### ISSUE TITLE
Check displays incorrectly in checkbox when zoomed

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#1292] opened 2019-01-13 01:50 UTC
**Describe the bug; what happened?**
Checkbox displays incorrectly when at certain zoom points.

**What are the steps to reproduce the issue?**
Go to the checkbox component and zoom the browser to 90%. Look at the check mark and see that the two lines don't properly intersect.

**What behavior did you expect?**
Check mark looks correct.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/943328/51080496-a2dd6c80-1691-11e9-8de5-2f8bf08d020f.png)

**In what environment did you see the issue?**
Chrome windows

**Comment by Falkicon** [comment] 2019-01-13 02:06
There also seems to be an issue with indeterminate at several zoom levels: 
![image](https://user-images.githubusercontent.com/943328/51080658-cb1a9a80-1694-11e9-871e-f68df1ac9f9f.png)

**Comment by Falkicon** [comment] 2019-01-13 03:00
And radio
![image](https://user-images.githubusercontent.com/943328/51081087-416ecb00-169c-11e9-8d7b-3a22cc493e0c.png)

**Comment by eljefe223** [comment] 2019-01-14 17:54
@Falkicon I think we can fix the checkmark issue by switching to a glyph but the indeterminate state might not be fixable. Same with the Radio. A glyph wont solve that issue.

**Comment by chrisdholt** [comment] 2019-04-20 20:11
Zoomed at 175%. I think this is solved for checkbox. I'm going to close this and take a look at radio. If the issue is still there on that, I'll create a new issue for that.

<img width="1336" alt="Screen Shot 2019-04-20 at 1 08 49 PM" src="https://user-images.githubusercontent.com/13071055/56461803-98f09700-636d-11e9-8b41-d5e1bcbb5ff0.png">

**Closed by chrisdholt** 2019-04-20 20:11 UTC
Labels: issue : bug
