### ISSUE TITLE
Update to improve code coverage

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#194] opened 2018-03-31 17:01 UTC
Desired code coverage should not include any warnings or errors. Additionally, all thresholds should be at least 80 or higher.  
"coverageThreshold": {
      "global": {
        "branches": 75,
        "functions": 95,
        "lines": 85,
        "statements": 85
        }
    },

**Comment by Falkicon** [comment] 2018-06-04 20:48
Duplicate of #192

**Comment by Falkicon** [comment] 2018-06-04 20:48
Duplicate #192

**Closed by Falkicon** 2018-06-04 20:48 UTC
Labels: contribute : help wanted, issue : task, reason : duplicate, tag : devops
