### ISSUE TITLE
Status bar showing wrong active component after refresh in fast-development-site-react

### ISSUE THREAD

**Issue by fmamic** [Microsoft/fast-dna#1303] opened 2019-01-15 22:19 UTC
**Describe the bug; what happened?**

Status bar is showing wrong active component after refreshing the page.

**What are the steps to reproduce the issue?**
1. "npm start" the "fast-components-react-base" package
2. Navigate to the Tabs component
3. Check status bar, should correctly display Tabs.
4. F5 (refresh)
5. Check status bar, it is showing Breadcrumb as active component.

**What behavior did you expect?**

Tabs component was selected and active and status bar should say Component: Tabs

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/9407124/51213423-e1ce2500-1912-11e9-9fa1-4616d95d5923.png)

**In what environment did you see the issue?**

Chrome

**Comment by chrisdholt** [comment] 2019-01-18 05:33
@kartik-budhiraja sure thing, feel free to send a PR! For some reason I can't assign to you, but I'll assign it out to myself to ensure it doesn't get picked up.

As an FYI, while the issue shows that this is repro'd in the fast-react-components-base package, the code with the issue is within the `fast-development-site-react` package, specifically in `src/site/index.tsx`.

Let us know if you have any questions!

**Comment by janechu** [comment] 2019-03-15 21:17
Fixed by #1513

**Closed by janechu** 2019-03-15 21:17 UTC
Labels: good first issue, issue : bug
