### ISSUE TITLE
Text with the caption element property selected is rendering centered and narrow

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#1273] opened 2019-01-08 10:14 UTC
On the caption component when caption element is used renders incorrectly.

**What are the steps to reproduce the issue?**
1. Go to the Caption component.
2. Select an example.
2. Choose caption from the HTML tag property menu in the configure form.
3. Observe odd formatting 

**What behavior did you expect?**
I expect the formatting to be correct.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/943328/50824132-913f4200-12ea-11e9-96a9-7a4a2b2d2b25.png)

**In what environment did you see the issue?**
Chrome on Windows

**Comment by nalogiudice** [comment] 2019-01-09 21:58
@Falkicon I know this seems incorrect in the examples, but the HTML `caption` element will only ever be the first child of a `table` element and therefore formatted correctly. See more [info](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption). I believe any style override based on the element would actually be incorrect. @chrisdholt I think we discussed this some months ago.

**Comment by chrisdholt** [comment] 2019-01-09 22:07
Correct - we get into trouble when we start modifying the display property to adjust for this issue in the tooling as that may create trouble when someone wants to use it within that context.

This is primarily a limitation of the tooling and the fact that this is within the context of a `div` with `display: block`

**Comment by nalogiudice** [comment] 2019-01-09 22:23
@chrisdholt as a test, I changed the overall caption class to be `display: block` and `text-align: left`, and then tested within a table, and it renders fine. So we could choose to do this, as it solved the [issue](https://github.com/Microsoft/fast-dna/issues/1274) of changing from `span` to `p` jumping a bit as well (because of change from `block` to `inline`.

**Comment by nalogiudice** [comment] 2019-01-09 22:36
Right. I was laying out the only other way to "fix" the issues. But, I think we are concluding that these are in fact not issues.

**Comment by chrisdholt** [comment] 2019-01-10 01:39
closing as by design

**Closed by chrisdholt** 2019-01-10 01:39 UTC
Labels: issue : bug
