### ISSUE TITLE
Export color values from MSFT styles package

### ISSUE THREAD

**Issue by brzho** [Microsoft/fast-dna#637] opened 2018-07-05 19:22 UTC
It would be nice to have color values exported from the MSFT styles package for design systems to consume. IE hex value definitions for common Microsoft colors.

**Comment by janechu** [comment] 2018-07-05 20:15
I agree, I think we could also tie this into the design system defaults.

**Comment by chrisdholt** [comment] 2018-09-11 21:51
Closing this as by design. Currently doesn't align with the intended goals of the MSFT package.

**Closed by chrisdholt** 2018-09-11 21:51 UTC
Labels: feature request, reason : by design
