### ISSUE TITLE
Fix "identical-code" issue in packages/fast-components-styles-msft/src/text-field/index.ts

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#406] opened 2018-05-10 20:35 UTC
Identical blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-styles-msft/src/text-field/index.ts#issue_5af4a5db650f240001000241

**Comment by nalogiudice** [comment] 2018-05-15 00:33
@awentzel - link 404s now

**Comment by chrisdholt** [comment] 2018-05-17 23:10
dupe of #447

**Closed by chrisdholt** 2018-05-17 23:10 UTC
Labels: triage
