### ISSUE TITLE
Create boilerplate commands for adding new components

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#79] opened 2018-03-14 22:49 UTC
We need to write a helper to facilitate this. Ideally we would run a command (eg. `npm run add-component`) and we would go through a series of prompts that generates all template files necessary, and also sets up imports in development apps.*

The process for adding components is the same except for the directory that they get added to. This guide focuses on components, but you can easily add a module by following these steps in the modules directory instead of the components directory.

**Comment by Falkicon** [comment] 2018-05-23 06:40
Is this a duplicate of "Create CLI to easily hook up new components#28"? If not, description should be updated to remove references to modules.

**Comment by chrisdholt** [comment] 2018-07-18 18:38
closing as a dupe of #28

**Closed as completed by chrisdholt** 2018-07-18 18:38 UTC
Labels: feature, closed:duplicate
