### ISSUE TITLE
Typography component should not apply color

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#733] opened 2018-07-24 23:46 UTC
The typography component should never manipulate the color of the text - the concern of typography is to apply font weight and height - all color should be controlled from outside of the component.

**Comment by chrisdholt** [comment] 2018-07-31 23:03
Based on recent conversations, to ensure that we accomplish our goals and to provide easy implementation, components will not inherit their color. Closing this as by design.

**Closed by chrisdholt** 2018-07-31 23:03 UTC
Labels: issue : bug, reason : by design
