### ISSUE TITLE
Update Text-field in configurator for improved UX

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#722] opened 2018-07-20 16:45 UTC
The configurator should be fixed so that it doesn't feel broken to users when on Text-Field component. I would expect that placeholder text gets replaced with specific text for each of the different input types. When selecting an input type the placeholder text should replace and the code preview should update.  Input types should not include date, range, or other non string/number types.

Usage and style guidance documentation should be updated to reflect current requirements.

**Comment by chrisdholt** [comment] 2018-09-13 05:07
Regarding: "Input types should not include date, range, or other non string/number types." has been solved with #875 for the time being and a future major release will remove them altogether #877.

Taking a deeper look at the request here, the configurator is working by design when looking at the text field component in the MSFT package. When configuring an instance of the component, you are working against a defined set of data and updating select parts of that data. `When selecting an input type the placeholder text should replace and the code preview should update.` With this ask being specific to text field, I think it works against all other instances of the configurator in the MSFT package. Changing in one instance would likely create a more confusing UX overall instead of an improved UX. 

If this is functionality that you'd like to see across all components, I think we should open a feature request specific to that. 

Closing this as by design.

**Closed by chrisdholt** 2018-09-13 05:07 UTC
Labels: reason : by design
