### ISSUE TITLE
Slight vertical shift on caption component when switching between p and span elements

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#1274] opened 2019-01-08 10:18 UTC
**Describe the bug; what happened?**

When viewing the caption component samples and changing from HTML tag span to p, it appears the line height shifts slightly. 

**What are the steps to reproduce the issue?**

1. Go to the caption component.
2. Click an example.
3. In the configure form, change the HTML tag from p to span.
4. Observe the vertical position shift slightly.

**What behavior did you expect?**

The line height should not shift.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

Chrome on Windows

**Comment by chrisdholt** [comment] 2019-01-09 22:17
@Falkicon this appears to be specifically related to moving from a `block` to an `inline` display element. I don't think we want to address this in the component as there are purposeful reasons for using the display properties from the browser.

**Comment by chrisdholt** [comment] 2019-01-10 01:39
Closing as by design

**Closed by chrisdholt** 2019-01-10 01:39 UTC
Labels: issue : bug
